### ISSUE TITLE
Hello, I modified pyproject.toml according to the method you provided and reconfigured the corresponding version of the package, but the error may be a version compatibility issue.

### ISSUE THREAD

**Issue by Harry969** [langchain-ai/streamlit-agent#35]
[tool.poetry]
name = "streamlit-agent"
version = "0.1.0"
description = ""
authors = ["Tim Conkling <tconkling@gmail.com>", "Joshua Carroll <joshua.carroll@snowflake.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "streamlit_agent"}]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
langchain = {version = ">=0.0.252", extras = ["docarray"]}
openai = "^0.27.8"
duckduckgo-search = "^3.8.3"
pypdf = "^3.12.2"
sentence-transformers = "^2.2.2"
torch = ">=2.0.0, !=2.0.1"
tabulate = "^0.9.0"  
streamlit-feedback = "^0.0.9"
langchain-experimental = "^0.0.10"
streamlit= ">=1.26"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.4.1"
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

> PS C:\Users\39627\Downloads\streamlit-agent-main> & c:/Users/39627/Downloads/streamlit-agent-main/langchain_env/Scripts/python.exe c:/Users/39627/Downloads/streamlit-agent-main/streamlit_agent/chat_with_documents.py
Traceback (most recent call last):
  File "c:\Users\39627\Downloads\streamlit-agent-main\streamlit_agent\chat_with_documents.py", line 4, in <module>
    from langchain.chat_models import ChatOpenAI
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\__init__.py", line 6, in <module>       
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\agents\__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\agents\agent.py", line 14, in <module>  
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\agents\agent_iterator.py", line 21, in <module>
    from langchain.callbacks.manager import (
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\callbacks\__init__.py", line 10, in <module>
    from langchain.callbacks.aim_callback import AimCallbackHandler 
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\callbacks\aim_callback.py", line 5, in <module>
    from langchain.schema import AgentAction, AgentFinish, LLMResult
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\schema\__init__.py", line 3, in <module>
    from langchain.schema.cache import BaseCache
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\schema\cache.py", line 6, in <module>   
    from langchain.schema.output import Generation
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\schema\output.py", line 7, in <module>  
    from langchain.load.serializable import Serializable
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\load\serializable.py", line 4, in <module>
    from langchain.pydantic_v1 import BaseModel, PrivateAttr        
ImportError: cannot import name 'PrivateAttr' from 'langchain.pydantic_v1' (C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\pydantic_v1\__init__.py)

**Comment by sfc-gh-jcarroll** [comment]
Fixed by https://github.com/langchain-ai/streamlit-agent/pull/37
